// Generated by `wit-bindgen` 0.36.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
//   * with "golem:llm/llm@1.0.0" = "golem_llm::golem::llm::llm"
//   * generate_unused_types
use golem_llm::golem::llm::llm as __with_name0;
#[cfg(target_arch = "wasm32")]
#[link_section = "component-type:wit-bindgen:0.36.0:golem:llm-openrouter@1.0.0:llm-library:encoded world"]
#[doc(hidden)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 1669] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\x83\x0c\x01A\x02\x01\
A\x02\x01BJ\x01m\x04\x04user\x09assistant\x06system\x04tool\x04\0\x04role\x03\0\0\
\x01m\x06\x0finvalid-request\x15authentication-failed\x13rate-limit-exceeded\x0e\
internal-error\x0bunsupported\x07unknown\x04\0\x0aerror-code\x03\0\x02\x01m\x06\x04\
stop\x06length\x0atool-calls\x0econtent-filter\x05error\x05other\x04\0\x0dfinish\
-reason\x03\0\x04\x01m\x03\x03low\x04high\x04auto\x04\0\x0cimage-detail\x03\0\x06\
\x01k\x07\x01r\x02\x03urls\x06detail\x08\x04\0\x09image-url\x03\0\x09\x01q\x02\x04\
text\x01s\0\x05image\x01\x0a\0\x04\0\x0ccontent-part\x03\0\x0b\x01ks\x01p\x0c\x01\
r\x03\x04role\x01\x04name\x0d\x07content\x0e\x04\0\x07message\x03\0\x0f\x01r\x03\
\x04names\x0bdescription\x0d\x11parameters-schemas\x04\0\x0ftool-definition\x03\0\
\x11\x01r\x03\x02ids\x04names\x0earguments-jsons\x04\0\x09tool-call\x03\0\x13\x01\
ky\x01r\x04\x02ids\x04names\x0bresult-jsons\x11execution-time-ms\x15\x04\0\x0cto\
ol-success\x03\0\x16\x01r\x04\x02ids\x04names\x0derror-messages\x0aerror-code\x0d\
\x04\0\x0ctool-failure\x03\0\x18\x01q\x02\x07success\x01\x17\0\x05error\x01\x19\0\
\x04\0\x0btool-result\x03\0\x1a\x01r\x02\x03keys\x05values\x04\0\x02kv\x03\0\x1c\
\x01kv\x01ps\x01k\x1f\x01p\x12\x01p\x1d\x01r\x07\x05models\x0btemperature\x1e\x0a\
max-tokens\x15\x0estop-sequences\x20\x05tools!\x0btool-choice\x0d\x10provider-op\
tions\"\x04\0\x06config\x03\0#\x01r\x03\x0cinput-tokens\x15\x0doutput-tokens\x15\
\x0ctotal-tokens\x15\x04\0\x05usage\x03\0%\x01k\x05\x01k&\x01r\x05\x0dfinish-rea\
son'\x05usage(\x0bprovider-id\x0d\x09timestamp\x0d\x16provider-metadata-json\x0d\
\x04\0\x11response-metadata\x03\0)\x01p\x14\x01r\x04\x02ids\x07content\x0e\x0ato\
ol-calls+\x08metadata*\x04\0\x11complete-response\x03\0,\x01r\x03\x04code\x03\x07\
messages\x13provider-error-json\x0d\x04\0\x05error\x03\0.\x01q\x03\x07message\x01\
-\0\x0ctool-request\x01+\0\x05error\x01/\0\x04\0\x0achat-event\x03\00\x01k\x0e\x01\
k+\x01r\x02\x07content2\x0atool-calls3\x04\0\x0cstream-delta\x03\04\x01q\x03\x05\
delta\x015\0\x06finish\x01*\0\x05error\x01/\0\x04\0\x0cstream-event\x03\06\x04\0\
\x0bchat-stream\x03\x01\x01h8\x01p7\x01k:\x01@\x01\x04self9\0;\x04\0\x1c[method]\
chat-stream.get-next\x01<\x01@\x01\x04self9\0:\x04\0%[method]chat-stream.blockin\
g-get-next\x01=\x01p\x10\x01@\x02\x08messages>\x06config$\01\x04\0\x04send\x01?\x01\
o\x02\x14\x1b\x01p\xc0\0\x01@\x03\x08messages>\x0ctool-results\xc1\0\x06config$\0\
1\x04\0\x08continue\x01B\x01i8\x01@\x02\x08messages>\x06config$\0\xc3\0\x04\0\x06\
stream\x01D\x04\0\x13golem:llm/llm@1.0.0\x05\0\x04\0&golem:llm-openrouter/llm-li\
brary@1.0.0\x04\0\x0b\x11\x01\0\x0bllm-library\x03\0\0\0G\x09producers\x01\x0cpr\
ocessed-by\x02\x0dwit-component\x070.220.0\x10wit-bindgen-rust\x060.36.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
