// Generated by `wit-bindgen` 0.36.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
//   * with "golem:llm/llm@1.0.0" = "golem_llm::golem::llm::llm"
//   * with "wasi:io/poll@0.2.0" = "golem_rust::wasm_rpc::wasi::io::poll"
//   * generate_unused_types
use golem_rust::wasm_rpc::wasi::io::poll as __with_name0;
use golem_llm::golem::llm::llm as __with_name1;
#[cfg(target_arch = "wasm32")]
#[link_section = "component-type:wit-bindgen:0.36.0:golem:llm-ollama@1.0.0:llm-library:encoded world"]
#[doc(hidden)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 1891] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xe1\x0d\x01A\x02\x01\
A\x05\x01B\x0a\x04\0\x08pollable\x03\x01\x01h\0\x01@\x01\x04self\x01\0\x7f\x04\0\
\x16[method]pollable.ready\x01\x02\x01@\x01\x04self\x01\x01\0\x04\0\x16[method]p\
ollable.block\x01\x03\x01p\x01\x01py\x01@\x01\x02in\x04\0\x05\x04\0\x04poll\x01\x06\
\x03\0\x12wasi:io/poll@0.2.0\x05\0\x02\x03\0\0\x08pollable\x01BO\x02\x03\x02\x01\
\x01\x04\0\x08pollable\x03\0\0\x01m\x04\x04user\x09assistant\x06system\x04tool\x04\
\0\x04role\x03\0\x02\x01m\x06\x0finvalid-request\x15authentication-failed\x13rat\
e-limit-exceeded\x0einternal-error\x0bunsupported\x07unknown\x04\0\x0aerror-code\
\x03\0\x04\x01m\x06\x04stop\x06length\x0atool-calls\x0econtent-filter\x05error\x05\
other\x04\0\x0dfinish-reason\x03\0\x06\x01m\x03\x03low\x04high\x04auto\x04\0\x0c\
image-detail\x03\0\x08\x01k\x09\x01r\x02\x03urls\x06detail\x0a\x04\0\x09image-ur\
l\x03\0\x0b\x01q\x02\x04text\x01s\0\x05image\x01\x0c\0\x04\0\x0ccontent-part\x03\
\0\x0d\x01ks\x01p\x0e\x01r\x03\x04role\x03\x04name\x0f\x07content\x10\x04\0\x07m\
essage\x03\0\x11\x01r\x03\x04names\x0bdescription\x0f\x11parameters-schemas\x04\0\
\x0ftool-definition\x03\0\x13\x01r\x03\x02ids\x04names\x0earguments-jsons\x04\0\x09\
tool-call\x03\0\x15\x01ky\x01r\x04\x02ids\x04names\x0bresult-jsons\x11execution-\
time-ms\x17\x04\0\x0ctool-success\x03\0\x18\x01r\x04\x02ids\x04names\x0derror-me\
ssages\x0aerror-code\x0f\x04\0\x0ctool-failure\x03\0\x1a\x01q\x02\x07success\x01\
\x19\0\x05error\x01\x1b\0\x04\0\x0btool-result\x03\0\x1c\x01r\x02\x03keys\x05val\
ues\x04\0\x02kv\x03\0\x1e\x01kv\x01ps\x01k!\x01p\x14\x01p\x1f\x01r\x07\x05models\
\x0btemperature\x20\x0amax-tokens\x17\x0estop-sequences\"\x05tools#\x0btool-choi\
ce\x0f\x10provider-options$\x04\0\x06config\x03\0%\x01r\x03\x0cinput-tokens\x17\x0d\
output-tokens\x17\x0ctotal-tokens\x17\x04\0\x05usage\x03\0'\x01k\x07\x01k(\x01r\x05\
\x0dfinish-reason)\x05usage*\x0bprovider-id\x0f\x09timestamp\x0f\x16provider-met\
adata-json\x0f\x04\0\x11response-metadata\x03\0+\x01p\x16\x01r\x04\x02ids\x07con\
tent\x10\x0atool-calls-\x08metadata,\x04\0\x11complete-response\x03\0.\x01r\x03\x04\
code\x05\x07messages\x13provider-error-json\x0f\x04\0\x05error\x03\00\x01q\x03\x07\
message\x01/\0\x0ctool-request\x01-\0\x05error\x011\0\x04\0\x0achat-event\x03\02\
\x01k\x10\x01k-\x01r\x02\x07content4\x0atool-calls5\x04\0\x0cstream-delta\x03\06\
\x01q\x03\x05delta\x017\0\x06finish\x01,\0\x05error\x011\0\x04\0\x0cstream-event\
\x03\08\x04\0\x0bchat-stream\x03\x01\x01h:\x01p9\x01k<\x01@\x01\x04self;\0=\x04\0\
\x1c[method]chat-stream.get-next\x01>\x01@\x01\x04self;\0<\x04\0%[method]chat-st\
ream.blocking-get-next\x01?\x01i\x01\x01@\x01\x04self;\0\xc0\0\x04\0\x1d[method]\
chat-stream.subscribe\x01A\x01p\x12\x01@\x02\x08messages\xc2\0\x06config&\03\x04\
\0\x04send\x01C\x01o\x02\x16\x1d\x01p\xc4\0\x01@\x03\x08messages\xc2\0\x0ctool-r\
esults\xc5\0\x06config&\03\x04\0\x08continue\x01F\x01i:\x01@\x02\x08messages\xc2\
\0\x06config&\0\xc7\0\x04\0\x06stream\x01H\x04\0\x13golem:llm/llm@1.0.0\x05\x02\x04\
\0\"golem:llm-ollama/llm-library@1.0.0\x04\0\x0b\x11\x01\0\x0bllm-library\x03\0\0\
\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit-component\x070.220.1\x10wit-bind\
gen-rust\x060.36.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
