package test:anthropic;

// See https://component-model.bytecodealliance.org/design/wit.html for more details about the WIT syntax

interface test-anthropic-api {
  add: func(value: u64);
  get: func() -> u64;
}

world test-anthropic {
  export test-anthropic-api;
}
