package test:grok;

// See https://component-model.bytecodealliance.org/design/wit.html for more details about the WIT syntax

interface test-grok-api {
  add: func(value: u64);
  get: func() -> u64;
}

world test-grok {
  export test-grok-api;
}
